### ISSUE TITLE
Some items that don't appear in the actual shop appears in the list

### ISSUE THREAD

**Issue by RL3D** [MasterL500/ShoppingList-geode#6]
![20240623035329_1](https://github.com/MasterL500/ShoppingList-geode/assets/93167795/4745f2da-7067-4e33-aa61-39ac2f4ff200)
A minor bug that shows an item not found in the shop

List of items:
- Ship 138
- Secondary Color 45
- Secondary Color 74

**Comment by MasterL500** [comment]
Thanks for letting me know, this error is now fixed in the next update
