### ISSUE TITLE
Wrong shop

### ISSUE THREAD

**Issue by RL3D** [MasterL500/ShoppingList-geode#7]
![20240623040223_1](https://github.com/MasterL500/ShoppingList-geode/assets/93167795/f01d1fcb-15c0-45c3-b691-23291fa3bfd7)
Another minor bug where the item shows up on the wrong shop on the list

Main Color 39 is the only item that is wrongly sorted. It's placed at the normal shop list instead of secret shop list.

**Comment by MasterL500** [comment]
Thanks for letting me know, this error is now fixed in the next update
